name: Build

# This action works with pull requests and pushes
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.2
      #   with:
      #     # This part is also where you can pass other options, for example:
      #     prettier_options: --write **/*.{ts,md}

      - name: run CI
        run: |
          npm install # or yarn install
          npm run lint # or yarn lint
          npm run test # or yarn test
          npm run build # or yarn build
